### ISSUE TITLE
Copying code from the tutorial includes "$" prompt

### ISSUE THREAD

**Issue by katharosada** [im-tomu/fomu-workshop#103]
On this page: http://workshop.fomu.im/en/latest/python.html

In this box:
![image](https://user-images.githubusercontent.com/4311392/71583389-7f176e80-2b0e-11ea-8c68-0f4fc088430c.png)

When you click copy, it includes the prompts.

**Comment by mithro** [comment]
@katharosada Could you check if this is still happening for you? If so, can you tell me what browser you are using.

**Comment by katharosada** [comment]
Still happening on Chrome Version 79.0.3945.88 (Official Build) (64-bit) on MacOSX

**Comment by ewenmcneill** [comment]
FTR, still happens for me on Firefox 72 on Linux as well.

See also https://github.com/im-tomu/fomu-workshop/issues/144 which is another user reporting the same issue.  Per https://github.com/im-tomu/fomu-workshop/issues/144#issuecomment-586143280 I think that "click to copy" Javascript is an anti-feature, so perhaps it can just be turned off in the documentation build?

Ewen

**Comment by eddygta17** [comment]
@mithro This issue seems to be resolved reading #144 and after testing the copy feature, it works.
