### ISSUE TITLE
Travis-CI Fails on Mac

### ISSUE THREAD

**Issue by xobs** [im-tomu/fomu-workshop#149]
Looks like Travis is failing on Mac builds for some reason.

**Comment by umarcor** [comment]
@xobs, is this still an issue? I'm hitting #212 in some PRs, but many other builds seem to work: https://travis-ci.com/github/im-tomu/fomu-workshop/builds.

**Comment by xobs** [comment]
It's definitely an issue, and is due to github throttling requests when doing the Mac build. Non-PR builds are authenticated, and therefore don't suffer from the same problem.

**Comment by umarcor** [comment]
What about using GitHub Actions instead of Travis CI?

**Comment by xobs** [comment]
That could work. I'm not sure how to set that up, or if it is exempt from throttling in a way that Travis is not.
