### ISSUE TITLE
enabled logging for sysbus.led

### ISSUE THREAD

**Issue by pdp7** [im-tomu/fomu-workshop#182]
In section: [Wishbone bridge between Renode and Fomu
](https://workshop.fomu.im/en/latest/renode-bridge.html
)
>The script you loaded configures Renode to log all communication with Fomu. After issuing some commands in Zephyr’s shell you’ll see:
> ```
> 01:00:31.8276 [DEBUG] led: [cpu: 0x40000988] WriteUInt32 to 0x8 (unknown), value 0x7.
> 01:00:31.8279 [DEBUG] led: [cpu: 0x40000990] WriteUInt32 to 0x4 (unknown), value 0x8.
> ```
However, I see no log output unless I run `sysbus LogPeripheralAccess sysbus.led`:
```
(monitor) include @scripts/complex/fomu/renode_etherbone_fomu.resc
(machine-0) start
Starting emulation...
(machine-0) sysbus LogPeripheralAccess sysbus.led
```
![Screenshot from 2020-03-02 14-07-12](https://user-images.githubusercontent.com/313864/75678980-10ca6600-5c8f-11ea-90c7-94c90c8c9c65.png)

**Comment by xobs** [comment]
Thanks for the patch.  In fda6bed5ca802c5b7fd9a8e267316bbbbaf9badf we now tell users to enable logging, as per your instructions.

**Comment by pdp7** [comment]
thanks @xobs
