### ISSUE TITLE
Broken links related to _static

### ISSUE THREAD

**Issue by tcal-x** [im-tomu/fomu-workshop#266]
On the page
https://workshop.fomu.im/en/latest/python.html
(https://github.com/im-tomu/fomu-workshop/blob/master/docs/python.rst)

Link "...(to be found for instance in [riscv-blink](https://workshop.fomu.im/en/latest/_static/riscv-blink/include/generated/csr.h))" points to "https://workshop.fomu.im/en/latest/_static/riscv-blink/include/generated/csr.h".

Link "...can be found in the [ICE40 LED Driver Usage Guide](https://workshop.fomu.im/en/latest/_static/reference/FPGA-TN-1288-ICE40LEDDriverUsageGuide.pdf)." points to "https://workshop.fomu.im/en/latest/_static/reference/FPGA-TN-1288-ICE40LEDDriverUsageGuide.pdf".

**Comment by tcal-x** [comment]
The link for ICE40 LED Driver now works, but the "riscv-blink" link is still broken.

**Comment by umarcor** [comment]
This was fixed in #350.

**Comment by tcal-x** [comment]
> This was fixed in #350.

Thanks @umarcor !
