### ISSUE TITLE
litex build usb does not emumerate

### ISSUE THREAD

**Issue by yorickvP** [im-tomu/fomu-workshop#33]
Using the fomu from camp
steps to reproduce:
```bash
cd litex
python3 workshop.py --lx-check-git --board hacker
dfu-util -D build/gateware/top.bin
```
dmesg output:
https://gist.github.com/yorickvP/c1500a88f424861d7a69a98177648b3c

**Comment by xobs** [comment]
Duplicate of #49 

Can you please try the latest version and see if it fixes this issue?

**Comment by yorickvP** [comment]
Yes! This fixes the issue! Thanks!
