### ISSUE TITLE
Block diagram has SPRAM mislabelled as PSRAM

### ISSUE THREAD

**Issue by dominicgs** [im-tomu/fomu-workshop#39]
This diagram: https://github.com/im-tomu/fomu-workshop/blob/master/img/fomu-block-diagram.png

It's SPRAM in the surrounding text but PSRAM in the ICE40 block on the diagram.

**Comment by xobs** [comment]
Thanks!  You're right, it should be SPRAM -- Single-Port RAM.

**Comment by umarcor** [comment]
Current location of the diagram: https://github.com/im-tomu/fomu-workshop/blob/master/docs/_static/fomu-block-diagram.png
