### ISSUE TITLE
Make the names in each row of the required software table links

### ISSUE THREAD

**Issue by mithro** [im-tomu/fomu-workshop#4]

**Comment by xobs** [comment]
Many of these don't have links.  For example, dfu-util usually comes from the package manager, and "serial console" is system-dependent.  Very few of these have binary downloads, which makes it not very useful for Mac or Windows users.

**Comment by mithro** [comment]
I'm think from a "get more information on this topic" type thing.

**Comment by xobs** [comment]
I added links to most of the ones that made sense.
