### ISSUE TITLE
Explain a LUT is N inputs to 1 output

### ISSUE THREAD

**Issue by mithro** [im-tomu/fomu-workshop#5]
And the iCE40 uses 4-input LUTs

**Comment by xobs** [comment]
Don't the Artix boards have 6-input 2-output LUTs?

**Comment by mithro** [comment]
Kinda... It is actually two LUT5s which share inputs and a MUX controlled by the 6th line. One output is the first LUT5, the second output is the MUX output.

**Comment by xobs** [comment]
Added a note towards the end of the section explaining them. If it's not accurate, please go ahead and revise it!
