### ISSUE TITLE
investigate docs ci failure

### ISSUE THREAD

**Issue by proppy** [im-tomu/fomu-workshop#518]
The doc build seems to have been failing on recently merged PRs:
https://github.com/im-tomu/fomu-workshop/runs/3193910380
https://readthedocs.org/projects/fomu-workshop/builds/14350395/

**Comment by umarcor** [comment]
I commented it with @mithro yesterday. He pointed me to https://github.com/SymbiFlow/symbiflow-examples/issues/169. It seems that @kgugala and @tcal-x have solved it in the last hours. However, I could not yet review what they did and how to apply it here.
