### ISSUE TITLE
can I --download while something else is running?

### ISSUE THREAD

**Issue by CarlFK** [im-tomu/fomu-workshop#61]
https://workshop.fomu.im/#loading-binaries
shows 
```
dfu-util -D file.dfu
...
To restart Fomu, unplug it and plug it back in. This will start the bootloader. To run the program on Fomu without needing to load it again, use the -e option:
```
is "restart Fomu" and "run the program on Fomu" the same thing?

The way I read that is: "unplug it and plug it back in" is the same as "use the -e option"  but I am very not sure.

**Comment by umarcor** [comment]
Closing in favour of #82.
