### ISSUE TITLE
Fix link to ICE40 LED docs

### ISSUE THREAD

**Issue by xobs** [im-tomu/fomu-workshop#81]
The page https://workshop.fomu.im/en/latest/python.html has a link at the bottom to https://workshop.fomu.im/en/latest/reference/FPGA-TN-1288-ICE40LEDDriverUsageGuide.pdf which is dead.

**Comment by mithro** [comment]
Fixed in https://github.com/im-tomu/fomu-workshop/commit/be9c062022aa1a615f30ac82a857b6830b296fd7 !
