### ISSUE TITLE
dfu fails

### ISSUE THREAD

**Issue by AnttiLukats** [im-tomu/fomu-workshop#9]
dfu-util.exe -D micropython-fomu.dfu

fails at 36%
dfuerror status(8) 

:(

**Comment by xobs** [comment]
This is more of a general Fomu question.  But can you try Fomu in a different USB port / hub?

**Comment by AnttiLukats** [comment]
yes, tried on different PC, there USB does not work at all

**Comment by xobs** [comment]
Which version of Fomu are you using?

**Comment by AnttiLukats** [comment]
I ha mistakenly used a tomu  with fomu the dfu works. Sorry stupid mistake
