### ISSUE TITLE
On some Fomu boards the SPI flash ID is returning as zero

### ISSUE THREAD

**Issue by mithro** [im-tomu/fomu-workshop#91]
```python
>>> spi = fomu.spi()
>>> hex(spi.id())
0x0
>>>
```
About 50% of people were hitting this at last night's workshop so it sounds like it has to do with the two flash types.

**Comment by xobs** [comment]
The issue is that micropython is hardcoded to use picospi, and doesn't know about the new lxspi implementation: https://github.com/xobs/micropython/blob/1dfed93b4d19c137c9accfd4ebb3fc28bd592a09/ports/fomu/src/spi.c#L20

**Comment by xobs** [comment]
Interestingly, if about 50% of people were hitting this, that means that 50% of people didn't update first.
