### ISSUE TITLE
Needless FIXME note in docs

### ISSUE THREAD

**Issue by ktopolski** [im-tomu/fomu-workshop#95]
Hello,

1st: thank you for FOMU and workshops - those are both awesome!
I stumbled upon the fixme note on page "http://workshop.fomu.im/en/latest/migen.html". I asked about it on workshop and got told to open the issue, so here it goes!

**Comment by umarcor** [comment]
This was done in https://github.com/im-tomu/fomu-workshop/commit/3f19ec183a975656757848da8d97b833ce5e1af8#diff-c7b5a4cf8240f5cefd3aa4f716fb6005b89f1e428ef9bd81ffe2f2a586677a32. I guess this issue can be closed.
